//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.10 at 12:29:08 AM YEKT 
//


package com.example.Archivist.wsdlclasess;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Ответ на запрос на смену пароля
 * 
 * <p>Java class for ChangePasswordResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChangePasswordResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.hostco.ru/reguser/types}AuthResponseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SNILS" type="{http://www.hostco.ru/reguser/types}SNILSType"/&gt;
 *         &lt;element name="temporary" type="{http://www.w3.org/2001/XMLSchema}boolean" maxOccurs="0" minOccurs="0"/&gt;
 *         &lt;element name="error" type="{http://www.hostco.ru/reguser/types}StandartResponseType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChangePasswordResponseType")
public class ChangePasswordResponseType
    extends AuthResponseType
{


}
