//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.10 at 12:29:08 AM YEKT 
//


package com.example.Archivist.wsdlclasess;

import javax.xml.bind.annotation.*;


/**
 * Ответ на запрос сведений о пользователе
 * 
 * <p>Java class for GetUserResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetUserResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SNILS" type="{http://www.hostco.ru/reguser/types}SNILSType" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="Login" type="{http://www.hostco.ru/reguser/types}LoginStrictType"/&gt;
 *           &lt;element name="Error" type="{http://www.hostco.ru/reguser/types}StandartResponseType"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="mcode" type="{http://www.hostco.ru/reguser/types}MuCodeType" minOccurs="0"/&gt;
 *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "getUserResponse", namespace = "http://www.hostco.ru/reguser")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetUserResponseType", propOrder = {
    "snils",
    "login",
    "error",
    "mcode",
    "gender"
})
public class GetUserResponseType {

    @XmlElement(name = "SNILS")
    protected String snils;
    @XmlElement(name = "Login")
    protected LoginStrictType login;
    @XmlElement(name = "Error")
    protected StandartResponseType error;
    protected String mcode;
    protected Integer gender;

    /**
     * Gets the value of the snils property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSNILS() {
        return snils;
    }

    /**
     * Sets the value of the snils property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSNILS(String value) {
        this.snils = value;
    }

    /**
     * Gets the value of the login property.
     * 
     * @return
     *     possible object is
     *     {@link LoginStrictType }
     *     
     */
    public LoginStrictType getLogin() {
        return login;
    }

    /**
     * Sets the value of the login property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoginStrictType }
     *     
     */
    public void setLogin(LoginStrictType value) {
        this.login = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link StandartResponseType }
     *     
     */
    public StandartResponseType getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandartResponseType }
     *     
     */
    public void setError(StandartResponseType value) {
        this.error = value;
    }

    /**
     * Gets the value of the mcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMcode() {
        return mcode;
    }

    /**
     * Sets the value of the mcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMcode(String value) {
        this.mcode = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGender(Integer value) {
        this.gender = value;
    }

}
