//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.10 at 12:29:08 AM YEKT 
//


package com.example.Archivist.wsdlclasess;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Базовые сведения о логине, атрибуты, обязательные при регистрации
 * 
 * <p>Java class for LoginStrictType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoginStrictType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.hostco.ru/reguser/types}LoginType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SNILS" type="{http://www.hostco.ru/reguser/types}SNILSType"/&gt;
 *         &lt;element name="Lastname" type="{http://www.hostco.ru/reguser/types}FIOType"/&gt;
 *         &lt;element name="Firstname" type="{http://www.hostco.ru/reguser/types}FIOType"/&gt;
 *         &lt;element name="Middlename" type="{http://www.hostco.ru/reguser/types}FIOType" minOccurs="0"/&gt;
 *         &lt;element name="BirthDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="Phone" type="{http://www.hostco.ru/reguser/types}PhoneType" minOccurs="0"/&gt;
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="PolicyNumber" type="{http://www.hostco.ru/reguser/types}PolicyNumberType" minOccurs="0"/&gt;
 *         &lt;element name="birthPlace" type="{http://www.hostco.ru/reguser/types}BirthPlaceType" minOccurs="0"/&gt;
 *         &lt;element name="documents" type="{http://www.hostco.ru/reguser/types}DocumentsType" minOccurs="0"/&gt;
 *         &lt;element name="children" type="{http://www.hostco.ru/reguser/types}ChildrenType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoginStrictType")
@XmlSeeAlso({
    RegUserRequestType.class
})
public class LoginStrictType
    extends LoginType
{


}
