//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.10 at 12:29:08 AM YEKT 
//


package com.example.Archivist.wsdlclasess;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.Archivist.wsdlclasess package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RegUserRequest_QNAME = new QName("http://www.hostco.ru/reguser", "regUserRequest");
    private final static QName _RegUserResponse_QNAME = new QName("http://www.hostco.ru/reguser", "regUserResponse");
    private final static QName _EditUserRequest_QNAME = new QName("http://www.hostco.ru/reguser", "editUserRequest");
    private final static QName _EditUserResponse_QNAME = new QName("http://www.hostco.ru/reguser", "editUserResponse");
    private final static QName _ResetPasswordRequest_QNAME = new QName("http://www.hostco.ru/reguser", "resetPasswordRequest");
    private final static QName _ResetPasswordResponse_QNAME = new QName("http://www.hostco.ru/reguser", "resetPasswordResponse");
    private final static QName _GetUserRequest_QNAME = new QName("http://www.hostco.ru/reguser", "getUserRequest");
    private final static QName _GetUserResponse_QNAME = new QName("http://www.hostco.ru/reguser", "getUserResponse");
    private final static QName _GetRolesRequest_QNAME = new QName("http://www.hostco.ru/reguser", "getRolesRequest");
    private final static QName _GetRolesResponse_QNAME = new QName("http://www.hostco.ru/reguser", "getRolesResponse");
    private final static QName _SetRolesRequest_QNAME = new QName("http://www.hostco.ru/reguser", "setRolesRequest");
    private final static QName _SetRolesResponse_QNAME = new QName("http://www.hostco.ru/reguser", "setRolesResponse");
    private final static QName _AuthUserRequest_QNAME = new QName("http://www.hostco.ru/reguser", "authUserRequest");
    private final static QName _AuthUserResponse_QNAME = new QName("http://www.hostco.ru/reguser", "authUserResponse");
    private final static QName _ChangePasswordRequest_QNAME = new QName("http://www.hostco.ru/reguser", "changePasswordRequest");
    private final static QName _ChangePasswordResponse_QNAME = new QName("http://www.hostco.ru/reguser", "changePasswordResponse");
    private final static QName _GetAccessCodeRequest_QNAME = new QName("http://www.hostco.ru/reguser", "getAccessCodeRequest");
    private final static QName _GetAccessCodeResponse_QNAME = new QName("http://www.hostco.ru/reguser", "getAccessCodeResponse");
    private final static QName _CheckAccessCodeRequest_QNAME = new QName("http://www.hostco.ru/reguser", "checkAccessCodeRequest");
    private final static QName _CheckAccessCodeResponse_QNAME = new QName("http://www.hostco.ru/reguser", "checkAccessCodeResponse");
    private final static QName _AddChildRequest_QNAME = new QName("http://www.hostco.ru/reguser", "addChildRequest");
    private final static QName _AddChildResponse_QNAME = new QName("http://www.hostco.ru/reguser", "addChildResponse");
    private final static QName _EditChildRequest_QNAME = new QName("http://www.hostco.ru/reguser", "editChildRequest");
    private final static QName _EditChildResponse_QNAME = new QName("http://www.hostco.ru/reguser", "editChildResponse");
    private final static QName _DeleteChildRequest_QNAME = new QName("http://www.hostco.ru/reguser", "deleteChildRequest");
    private final static QName _DeleteChildResponse_QNAME = new QName("http://www.hostco.ru/reguser", "deleteChildResponse");
    private final static QName _RegCallUserRequest_QNAME = new QName("http://www.hostco.ru/reguser/types", "regCallUserRequest");
    private final static QName _RegReqUserResponse_QNAME = new QName("http://www.hostco.ru/reguser/types", "regReqUserResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.Archivist.wsdlclasess
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StandartResponseType }
     * 
     */
    public StandartResponseType createStandartResponseType() {
        return new StandartResponseType();
    }

    /**
     * Create an instance of {@link StandartResponseType.ErrorList }
     * 
     */
    public StandartResponseType.ErrorList createStandartResponseTypeErrorList() {
        return new StandartResponseType.ErrorList();
    }

    /**
     * Create an instance of {@link RegUserRequestType }
     * 
     */
    public RegUserRequestType createRegUserRequestType() {
        return new RegUserRequestType();
    }

    /**
     * Create an instance of {@link RegUserResponseType }
     * 
     */
    public RegUserResponseType createRegUserResponseType() {
        return new RegUserResponseType();
    }

    /**
     * Create an instance of {@link EditUserRequestType }
     * 
     */
    public EditUserRequestType createEditUserRequestType() {
        return new EditUserRequestType();
    }

    /**
     * Create an instance of {@link EditUserResponseType }
     * 
     */
    public EditUserResponseType createEditUserResponseType() {
        return new EditUserResponseType();
    }

    /**
     * Create an instance of {@link ResetPasswordRequestType }
     * 
     */
    public ResetPasswordRequestType createResetPasswordRequestType() {
        return new ResetPasswordRequestType();
    }

    /**
     * Create an instance of {@link ResetPasswordResponseType }
     * 
     */
    public ResetPasswordResponseType createResetPasswordResponseType() {
        return new ResetPasswordResponseType();
    }

    /**
     * Create an instance of {@link GetUserRequestType }
     * 
     */
    public GetUserRequestType createGetUserRequestType() {
        return new GetUserRequestType();
    }

    /**
     * Create an instance of {@link GetUserResponseType }
     * 
     */
    public GetUserResponseType createGetUserResponseType() {
        return new GetUserResponseType();
    }

    /**
     * Create an instance of {@link GetRolesRequestType }
     * 
     */
    public GetRolesRequestType createGetRolesRequestType() {
        return new GetRolesRequestType();
    }

    /**
     * Create an instance of {@link GetRolesResponseType }
     * 
     */
    public GetRolesResponseType createGetRolesResponseType() {
        return new GetRolesResponseType();
    }

    /**
     * Create an instance of {@link SetRolesRequestType }
     * 
     */
    public SetRolesRequestType createSetRolesRequestType() {
        return new SetRolesRequestType();
    }

    /**
     * Create an instance of {@link SetRolesResponseType }
     * 
     */
    public SetRolesResponseType createSetRolesResponseType() {
        return new SetRolesResponseType();
    }

    /**
     * Create an instance of {@link AuthRequestType }
     * 
     */
    public AuthRequestType createAuthRequestType() {
        return new AuthRequestType();
    }

    /**
     * Create an instance of {@link AuthResponseType }
     * 
     */
    public AuthResponseType createAuthResponseType() {
        return new AuthResponseType();
    }

    /**
     * Create an instance of {@link ChangePasswordRequestType }
     * 
     */
    public ChangePasswordRequestType createChangePasswordRequestType() {
        return new ChangePasswordRequestType();
    }

    /**
     * Create an instance of {@link ChangePasswordResponseType }
     * 
     */
    public ChangePasswordResponseType createChangePasswordResponseType() {
        return new ChangePasswordResponseType();
    }

    /**
     * Create an instance of {@link GetAccessCodeRequestType }
     * 
     */
    public GetAccessCodeRequestType createGetAccessCodeRequestType() {
        return new GetAccessCodeRequestType();
    }

    /**
     * Create an instance of {@link GetAccessCodeResponseType }
     * 
     */
    public GetAccessCodeResponseType createGetAccessCodeResponseType() {
        return new GetAccessCodeResponseType();
    }

    /**
     * Create an instance of {@link CheckAccessCodeRequestType }
     * 
     */
    public CheckAccessCodeRequestType createCheckAccessCodeRequestType() {
        return new CheckAccessCodeRequestType();
    }

    /**
     * Create an instance of {@link ParentType }
     * 
     */
    public ParentType createParentType() {
        return new ParentType();
    }

    /**
     * Create an instance of {@link ChildrenType }
     * 
     */
    public ChildrenType createChildrenType() {
        return new ChildrenType();
    }

    /**
     * Create an instance of {@link DocumentsType }
     * 
     */
    public DocumentsType createDocumentsType() {
        return new DocumentsType();
    }

    /**
     * Create an instance of {@link WarningListType }
     * 
     */
    public WarningListType createWarningListType() {
        return new WarningListType();
    }

    /**
     * Create an instance of {@link WarningType }
     * 
     */
    public WarningType createWarningType() {
        return new WarningType();
    }

    /**
     * Create an instance of {@link StringID }
     * 
     */
    public StringID createStringID() {
        return new StringID();
    }

    /**
     * Create an instance of {@link IntID }
     * 
     */
    public IntID createIntID() {
        return new IntID();
    }

    /**
     * Create an instance of {@link DocIdType }
     * 
     */
    public DocIdType createDocIdType() {
        return new DocIdType();
    }

    /**
     * Create an instance of {@link RoleType }
     * 
     */
    public RoleType createRoleType() {
        return new RoleType();
    }

    /**
     * Create an instance of {@link RoleListType }
     * 
     */
    public RoleListType createRoleListType() {
        return new RoleListType();
    }

    /**
     * Create an instance of {@link UserIDType }
     * 
     */
    public UserIDType createUserIDType() {
        return new UserIDType();
    }

    /**
     * Create an instance of {@link LoginType }
     * 
     */
    public LoginType createLoginType() {
        return new LoginType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link ChildType }
     * 
     */
    public ChildType createChildType() {
        return new ChildType();
    }

    /**
     * Create an instance of {@link LoginStrictType }
     * 
     */
    public LoginStrictType createLoginStrictType() {
        return new LoginStrictType();
    }

    /**
     * Create an instance of {@link TmpPasswordResponseType }
     * 
     */
    public TmpPasswordResponseType createTmpPasswordResponseType() {
        return new TmpPasswordResponseType();
    }

    /**
     * Create an instance of {@link StandartResponseType.ErrorList.RecordError }
     * 
     */
    public StandartResponseType.ErrorList.RecordError createStandartResponseTypeErrorListRecordError() {
        return new StandartResponseType.ErrorList.RecordError();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegUserRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RegUserRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "regUserRequest")
    public JAXBElement<RegUserRequestType> createRegUserRequest(RegUserRequestType value) {
        return new JAXBElement<RegUserRequestType>(_RegUserRequest_QNAME, RegUserRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegUserResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RegUserResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "regUserResponse")
    public JAXBElement<RegUserResponseType> createRegUserResponse(RegUserResponseType value) {
        return new JAXBElement<RegUserResponseType>(_RegUserResponse_QNAME, RegUserResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EditUserRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link EditUserRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "editUserRequest")
    public JAXBElement<EditUserRequestType> createEditUserRequest(EditUserRequestType value) {
        return new JAXBElement<EditUserRequestType>(_EditUserRequest_QNAME, EditUserRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EditUserResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link EditUserResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "editUserResponse")
    public JAXBElement<EditUserResponseType> createEditUserResponse(EditUserResponseType value) {
        return new JAXBElement<EditUserResponseType>(_EditUserResponse_QNAME, EditUserResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResetPasswordRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ResetPasswordRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "resetPasswordRequest")
    public JAXBElement<ResetPasswordRequestType> createResetPasswordRequest(ResetPasswordRequestType value) {
        return new JAXBElement<ResetPasswordRequestType>(_ResetPasswordRequest_QNAME, ResetPasswordRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResetPasswordResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ResetPasswordResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "resetPasswordResponse")
    public JAXBElement<ResetPasswordResponseType> createResetPasswordResponse(ResetPasswordResponseType value) {
        return new JAXBElement<ResetPasswordResponseType>(_ResetPasswordResponse_QNAME, ResetPasswordResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUserRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetUserRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "getUserRequest")
    public JAXBElement<GetUserRequestType> createGetUserRequest(GetUserRequestType value) {
        return new JAXBElement<GetUserRequestType>(_GetUserRequest_QNAME, GetUserRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUserResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetUserResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "getUserResponse")
    public JAXBElement<GetUserResponseType> createGetUserResponse(GetUserResponseType value) {
        return new JAXBElement<GetUserResponseType>(_GetUserResponse_QNAME, GetUserResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetRolesRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetRolesRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "getRolesRequest")
    public JAXBElement<GetRolesRequestType> createGetRolesRequest(GetRolesRequestType value) {
        return new JAXBElement<GetRolesRequestType>(_GetRolesRequest_QNAME, GetRolesRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetRolesResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetRolesResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "getRolesResponse")
    public JAXBElement<GetRolesResponseType> createGetRolesResponse(GetRolesResponseType value) {
        return new JAXBElement<GetRolesResponseType>(_GetRolesResponse_QNAME, GetRolesResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetRolesRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SetRolesRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "setRolesRequest")
    public JAXBElement<SetRolesRequestType> createSetRolesRequest(SetRolesRequestType value) {
        return new JAXBElement<SetRolesRequestType>(_SetRolesRequest_QNAME, SetRolesRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetRolesResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SetRolesResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "setRolesResponse")
    public JAXBElement<SetRolesResponseType> createSetRolesResponse(SetRolesResponseType value) {
        return new JAXBElement<SetRolesResponseType>(_SetRolesResponse_QNAME, SetRolesResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AuthRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "authUserRequest")
    public JAXBElement<AuthRequestType> createAuthUserRequest(AuthRequestType value) {
        return new JAXBElement<AuthRequestType>(_AuthUserRequest_QNAME, AuthRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AuthResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "authUserResponse")
    public JAXBElement<AuthResponseType> createAuthUserResponse(AuthResponseType value) {
        return new JAXBElement<AuthResponseType>(_AuthUserResponse_QNAME, AuthResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangePasswordRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ChangePasswordRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "changePasswordRequest")
    public JAXBElement<ChangePasswordRequestType> createChangePasswordRequest(ChangePasswordRequestType value) {
        return new JAXBElement<ChangePasswordRequestType>(_ChangePasswordRequest_QNAME, ChangePasswordRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangePasswordResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ChangePasswordResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "changePasswordResponse")
    public JAXBElement<ChangePasswordResponseType> createChangePasswordResponse(ChangePasswordResponseType value) {
        return new JAXBElement<ChangePasswordResponseType>(_ChangePasswordResponse_QNAME, ChangePasswordResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAccessCodeRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetAccessCodeRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "getAccessCodeRequest")
    public JAXBElement<GetAccessCodeRequestType> createGetAccessCodeRequest(GetAccessCodeRequestType value) {
        return new JAXBElement<GetAccessCodeRequestType>(_GetAccessCodeRequest_QNAME, GetAccessCodeRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAccessCodeResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetAccessCodeResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "getAccessCodeResponse")
    public JAXBElement<GetAccessCodeResponseType> createGetAccessCodeResponse(GetAccessCodeResponseType value) {
        return new JAXBElement<GetAccessCodeResponseType>(_GetAccessCodeResponse_QNAME, GetAccessCodeResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckAccessCodeRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CheckAccessCodeRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "checkAccessCodeRequest")
    public JAXBElement<CheckAccessCodeRequestType> createCheckAccessCodeRequest(CheckAccessCodeRequestType value) {
        return new JAXBElement<CheckAccessCodeRequestType>(_CheckAccessCodeRequest_QNAME, CheckAccessCodeRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StandartResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StandartResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "checkAccessCodeResponse")
    public JAXBElement<StandartResponseType> createCheckAccessCodeResponse(StandartResponseType value) {
        return new JAXBElement<StandartResponseType>(_CheckAccessCodeResponse_QNAME, StandartResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ParentType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "addChildRequest")
    public JAXBElement<ParentType> createAddChildRequest(ParentType value) {
        return new JAXBElement<ParentType>(_AddChildRequest_QNAME, ParentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StandartResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StandartResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "addChildResponse")
    public JAXBElement<StandartResponseType> createAddChildResponse(StandartResponseType value) {
        return new JAXBElement<StandartResponseType>(_AddChildResponse_QNAME, StandartResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ParentType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "editChildRequest")
    public JAXBElement<ParentType> createEditChildRequest(ParentType value) {
        return new JAXBElement<ParentType>(_EditChildRequest_QNAME, ParentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StandartResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StandartResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "editChildResponse")
    public JAXBElement<StandartResponseType> createEditChildResponse(StandartResponseType value) {
        return new JAXBElement<StandartResponseType>(_EditChildResponse_QNAME, StandartResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParentType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ParentType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "deleteChildRequest")
    public JAXBElement<ParentType> createDeleteChildRequest(ParentType value) {
        return new JAXBElement<ParentType>(_DeleteChildRequest_QNAME, ParentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StandartResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link StandartResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser", name = "deleteChildResponse")
    public JAXBElement<StandartResponseType> createDeleteChildResponse(StandartResponseType value) {
        return new JAXBElement<StandartResponseType>(_DeleteChildResponse_QNAME, StandartResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegUserRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RegUserRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser/types", name = "regCallUserRequest")
    public JAXBElement<RegUserRequestType> createRegCallUserRequest(RegUserRequestType value) {
        return new JAXBElement<RegUserRequestType>(_RegCallUserRequest_QNAME, RegUserRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegUserResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RegUserResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.hostco.ru/reguser/types", name = "regReqUserResponse")
    public JAXBElement<RegUserResponseType> createRegReqUserResponse(RegUserResponseType value) {
        return new JAXBElement<RegUserResponseType>(_RegReqUserResponse_QNAME, RegUserResponseType.class, null, value);
    }

}
